### ISSUE TITLE
scimilarity_gred missing

### ISSUE THREAD

**Issue by steinse5** [Genentech/pascient#1]
Hi, I just tried to install pascient but could not find the required scimilarity_gred package.
Could you please point me to the missing package? 
Many thanks in advance!

**Comment by HelloWorldLTY** [comment]
Hi, thanks for your interests of our work. Would you please try to replace the package of scimilarity_gred with scimilarity and try to replace the codes requiring scimilarity_gred with the functions in this file: https://github.com/Genentech/scimilarity/blob/main/src/scimilarity/utils.py? I think scimilarity_gred is an internal version and may not be released right now. Please let me know if this solution can work for you.

**Comment by HelloWorldLTY** [comment]
Hi, this error should be fixed based on the new pull request. Thanks for pointing it out.
